version: '3'

tasks:
  pull:
    desc: Pull the base r-devel-san image
    cmds:
      - podman pull docker.io/rocker/r-devel-san:latest
      - podman tag docker.io/rocker/r-devel-san:latest r-devel-san:latest

  build:
    desc: Build the Docker image
    cmds:
      - podman build --tag r-devel-san-cmake -f ./Dockerfile

  run:
    desc: Run the Docker image
    cmds:
      - podman run --rm -it localhost/r-devel-san-cmake:latest bash
